server:
  port: 8085
spring:
  servlet:
    multipart:
      max-file-size : 10MB
      max-request-size : 10MB
  redis:
    host: 127.0.0.1
    port: 6379
    #password: 123456
    timeout: 5000ms # 连接超时时间（毫秒）
    lettuce:
      pool:
        max-active: 20 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
        max-wait: 5000ms # 连接池最大阻塞等待时间（使用负值表示没有限制）

# DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3310/errorbook?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      # 连接池中允许的最小连接数。default：10
      minimum-idle: 10
      # 连接池中允许的最大连接数。default：10
      maximum-pool-size: 30
      # 自动提交 默认是 true，自动提交从池中返回的连接
      auto-commit: true
      # 一个连接idle状态的最大时长（毫秒），超时则被释放（retired），default:10minutes
      idle-timeout: 60000
      # 连接池名字
      #pool-name: "Hikari01"
      # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），default:30minutes，建议设置比数据库超时时长少30秒
      max-lifetime: 1800000
      # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， default:30秒
      connection-timeout: 20000

config:
  jwt:
    secret: f4e2e52034348f86b67cde581c0f9eb6
    expire: 72000000 #20小时
    header: token

#RestTemplateConfig
rest:
  connectTimeout: 60000
  readTimeout: 300000
  connectionRequestTimeout: 300000